# alias nvim='nvim --listen /tmp/nvim-server.pipe'
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-send "<C-\><C-N>:tabe +{{line}} $(pwd)/{{filename}}<CR>"'

gui:
  theme:
    selectedLineBgColor:
      - underline 
    selectedRangeBgColor:
      - underline

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

# git:
#   paging:
#     colorArg: always
#     useConfig: true

# keybinding:
#   universal:
#     scrollLeft: '<c-h>' # scroll left within list view
#     scrollRight: '<c-l>' # scroll right within list view
